### ISSUE TITLE
Importing with Postgres enum types

### ISSUE THREAD

**Issue by Heliozoa** [getsynth/synth#104]
Thanks for your work on synth!

**Required Functionality**
Currently, trying to import from a database that uses enum types, e.g.
```sql
CREATE TYPE MyType AS ENUM ('Left', 'Right');
CREATE TABLE my_table (my_type MyType);
```
results in
```console
Error: We haven't implemented a converter for mytype
```

**Use case**
I have a database where some Rust enums are represented as enum types and it would be nice to be able to use synth's import feature with it.

**Comment by christoshadjiaslanis** [comment]
Hey @Heliozoa - thanks for taking the time to write this up.

Even though you are correct in saying that we don't support Enums as a type, you've basically stumbled on the fact that we don't support user-defined types in general. Currently we just get the type name from the database (in this case `mytype`) and pattern match against a list of known types. Obviously since your type is user defined we're not matching against it.

We need to use the `sqlx` [PGTypeKind](https://docs.rs/sqlx/0.5.5/sqlx/postgres/enum.PgTypeKind.html) enum to support composite user-defined types.

Thanks for bringing this up, we need to fit it into the roadmap soon.
