### ISSUE TITLE
Feature: Scheduler / Topological sorting namespaces

### ISSUE THREAD

**Issue by llogiq** [getsynth/synth#29]
**Required Functionality**
synth as of now requires the namespaces to be in order when having dependencies (for example by foreign key relations in a database) between them. A [topological sort](https://en.wikipedia.org/wiki/Topological_sorting) would solve this. 

**Proposed Solution**
The most used algorithm is Kahn's which the [toposort-scc](https://crates.io/crates/toposort-scc) crate already implements. An implementation could either (in accordance with the Apache-2.0 license) be derived from that or depend on the crate.

**Use case**
With the topological sort and a function to know whether a namespace depends on another, we may even parallelize generation for multiple namespaces.This would also incidentally allow us to emit a good error message if the dependency graph between namespaces is cyclic.

**Comment by christoshadjiaslanis** [comment]
The design / implementation of the scheduler is up to the author . It is also important to mention that for now this should cover 'collection-level' FK constraints (this distinction is important because the scheduler would be significantly more complex to handle constraints on arbitrary document structures).

A good starting point would be implementing the function Namespace::topo_sort(&self) -> Option<Vec<Name>>  (or maybe Result?) which outputs an ordered list of collection names. The adjacency list can be built by identifying the same_as content nodes in a given namespace. This list of collection names can then be used as an iterator in various Export implementations (e.g. postgres) to ensure correct insertion order of samples.

Further optimisations could include parallel insertion by finding all leaves of the Namespace and working up towards the collections.

**Comment by OLUWAMUYIWA** [comment]
Is this okay as a first contribution?

**Comment by christoshadjiaslanis** [comment]
@OLUWAMUYIWA for sure. If you need any help / clarification feel free to join our Discord server and we can work on the implementation.

**Comment by OLUWAMUYIWA** [comment]
Okay then. I'm sliding in.

**Comment by OLUWAMUYIWA** [comment]
I created a PR on #49 . Please check and tell me if its okay. Thanks!

**Comment by brokad** [comment]
Closing this as it was merged with #49. Thanks again @OLUWAMUYIWA, you're a legend :smile:
